language: rust
rust:
  - stable
os:
- linux
addons:
  apt:
    packages:
    - libudev-dev
cache:
  - cargo
  - apt
jobs:
  fast_finish: true
  include:
    - stage: build
      name: "Linux (64bit)"
      env:
        - BINARY_EXTENSION=
        - TARGET=x86_64-unknown-linux-gnu
    - stage: build
      name: "Windows (32bit)"
      install: rustup target add i686-pc-windows-gnu
      env:
        - TARGET=i686-pc-windows-gnu
        - BINARY_EXTENSION=.exe
      addons:
        apt:
          packages:
          - gcc-mingw-w64-i686
    - stage: build
      name: "Windows (64bit)"
      install: rustup target add i686-pc-windows-gnu
      env:
        - TARGET=x86_64-pc-windows-gnu
        - BINARY_EXTENSION=.exe
      addons:
        apt:
          packages:
          - gcc-mingw-w64-x86-64

script:
  - cargo build --target $TARGET --verbose --release
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
  - "target/$TARGET/release/ddcset-stripped$BINARY_EXTENSION"
  cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable"
before_deploy:
  - strip -o "target/$TARGET/release/ddcset-stripped$BINARY_EXTENSION" "target/$TARGET/release/ddcset$BINARY_EXTENSION"